/*************JavaScript----Start***************/

// Variable---Declared

// fullName="Shreya";
// age="26";
// console.log("fullName = ",fullName,"//  age = ",age)

// Dynamically---Typed

// fullName="Shreya";
// age=23;
// console.log(fullName,age)

// fullName="Rimjhim";
// console.log(fullName,age)

// Lets--Var--Const

// let age=24;
// let age=29; // twoTime sameVariable canNot beDeclared
// console.log(age);// Error

// let age=24;
// age=56;
// console.log(age);// 56

// var age=21;
// var age=47;
// console.log(age); // 47

// const age=56;
// age=90;
// console.log(age); // Error

// let age;
// console.log(age);

// const age;
// console.log(age);

// Block Variable {}

// {
//     let age=9;
//     console.log(age);

// }

// {
//     let age=10;
//     console.log(age);

// }

// Objects 

// const student={
//     fullName: 'rahul sharma',
//     age:20,
// }
// console.log(student);
// console.log(student.age);
// console.log(student["age"]);



// Operators--[Arithematics]

// let a=23;
// let b=18;
// console.log("a+b=",a+b) //addition
// console.log("a-b=",a-b) // substraction
// console.log("a*b=",a*b) // multiplication
// console.log("a/b=",a/b) // divided
// console.log("a**b=",a**b) // exponent
// console.log("a%b=",a%b) // modules


// let r=8;

// console.log(r++);
// console.log(r);
// console.log(++r);
// console.log(--r);
// console.log(r--);
// console.log(r);


// Assignment Operators

// let a=8;
// a+=4;
// console.log(a);
// a-=2;
// console.log(a);
// a*=5;
// console.log(a);
// a/=10;
// console.log(a);

// comparison Operator

// let a=8;
// let b=9;
// console.log(a==b); // false
// console.log(a!=b); // True

// if else statement
// {
// let age=27;
// if (age>=18){
//     console.log("You can Vote")
// }
// else{console.log("You cannot Vote")}

// }



// myOwn createdCode



// {
//     let age= prompt("TYPE YOUR AGE : ");
//     if (age>=18){
//         console.log("You Can Vote !!!")
//     } 
//     else{console.log("You Cannot Vote ..")}

// }

// Grade for School Student

let marks=23;
if (marks>100){
    console.log("Invalid Number, Please put Verified Marks")
}
else if (marks>=80){
    console.log("Your Grade is A+")
}else if (marks>=70){
    console.log("Your Grade is B+")
}else if (marks>=60){
    console.log("Your Grade is C+")
}else if (marks>=50){
    console.log("Your Grade is D+")
}else{
    console.log("Your Grade is F ")
}























